name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: make
      run: make
    - name: Upload Artifact
      uses: actions/upload-artifact@v2.2.3
      with:
        # Artifact name
        name: binary
        # A file, directory or wildcard pattern that describes what to upload
        path: test
